# Generated by Django 4.0.3 on 2022-04-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique', '0002_alter_unique_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique',
            name='price',
            field=models.CharField(max_length=120),
        ),
    ]
